### ISSUE TITLE
restart on finish/completion 

### ISSUE THREAD

**Issue by unlacedla** [OmarKhattab/shopifymonitor#1]
hey, I've implemented the discord webhook into your kith monitor, its working lovely but I  was wondering if you could help me implement a restart on completion bc once it says the products haven't restocked it just stops, id love to run It 24.7 on a server if we can implement this. thank you! otherwise its working amazing <3

**Comment by unlacedla** [comment]
nvm im dumb, just realized... pm2 start kith works perfect. thank you again!

**Comment by OmarKhattab** [comment]
closing this since you found a solution feel free to document what you did here.
